### ISSUE TITLE
Malformed regex errors when searching for keywords with unbalanced parenthesis

### ISSUE THREAD

**Issue by martinscooper** [label-sleuth/label-sleuth#204]
**What is the current behavior?**
Using the search panel with a malformed regex fails. For example: querying for a string that contains `)` returns the following trace:

```
Traceback (most recent call last):
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/authentication.py", line 32, in wrapper
    return function(*args, **kwargs)
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/app_utils.py", line 36, in wrapper
    return function(workspace_id, *args, **kwargs)
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/app.py", line 539, in query
    resp = curr_app.orchestrator_api.query(workspace_id, dataset_name, category_id=None, query_regex=query_string,
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/orchestrator/orchestrator_api.py", line 246, in query
    return self.data_access.get_text_elements(workspace_id=workspace_id, dataset_name=dataset_name,
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/data_access/file_based/file_based_data_access.py", line 249, in get_text_elements
    self._get_text_elements(
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/data_access/file_based/file_based_data_access.py", line 482, in _get_text_elements
    corpus_df = filter_func(corpus_df, labels_series)
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/data_access/file_based/file_based_data_access.py", line 251, in <lambda>
    filter_func=lambda df, _: utils.filter_by_query_and_document_uri(df, query_regex, document_uri),
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/data_access/file_based/utils.py", line 75, in filter_by_query_and_document_uri
    return df[df.text.str.contains(query, flags=re.IGNORECASE, na=False)]
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 101, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 1110, in contains
    result = self._data.array._str_contains(pat, case, flags, na, regex)
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/pandas/core/strings/object_array.py", line 110, in _str_contains
    regex = re.compile(pat, flags=flags)
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/martin/opt/miniconda3/envs/label-sleuth/lib/python3.8/sre_parse.py", line 962, in parse
    raise source.error("unbalanced parenthesis")
re.error: unbalanced parenthesis at position 5
```

**What is the expected behavior?**
The backend should treat the query string as normal text if parsing the input as a regex fails. However, is the user was indeed trying to search for a regex searching for the text instead may be confusing. We can add a checkbox that lets the user specify that they are inputing a regex.

**Comment by martinscooper** [comment]
This issue doesn't exist in the current system version as the search input is treated as a string by default. An issue proposing how to re-enable is going to be created soon.
