### ISSUE TITLE
Error when deleting workspace

### ISSUE THREAD

**Issue by martinscooper** [label-sleuth/label-sleuth#250]
**What is the current behavior?**
Sometimes, deleting a workspace fails.

Request:
![image](https://user-images.githubusercontent.com/22247838/194351707-94964ac1-64ed-48c0-9767-91ed21492241.png)

Error stacktrace: 
```python
2022-10-06 12:15:01,574 ERROR    [orchestrator_api.py:101] error deleting workspace 'www'
Traceback (most recent call last):
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/orchestrator/orchestrator_api.py", line 98, in delete_workspace
    self._delete_category_models(workspace_id, category_id)
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/orchestrator/orchestrator_api.py", line 341, in _delete_category_models
    for idx in range(len(workspace.categories[category_id].iterations)):
AttributeError: 'NoneType' object has no attribute 'iterations'
2022-10-06 12:15:01,575 ERROR    [app.py:1455] Exception on /workspace/www [DELETE]
Traceback (most recent call last):
  File "/Users/martin/opt/miniconda3/envs/label-sleuth-test/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/martin/opt/miniconda3/envs/label-sleuth-test/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/martin/opt/miniconda3/envs/label-sleuth-test/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/martin/opt/miniconda3/envs/label-sleuth-test/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/martin/opt/miniconda3/envs/label-sleuth-test/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/authentication.py", line 32, in wrapper
    return function(*args, **kwargs)
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/app_utils.py", line 36, in wrapper
    return function(workspace_id, *args, **kwargs)
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/app.py", line 246, in delete_workspace
    curr_app.orchestrator_api.delete_workspace(workspace_id)
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/orchestrator/orchestrator_api.py", line 102, in delete_workspace
    raise e
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/orchestrator/orchestrator_api.py", line 98, in delete_workspace
    self._delete_category_models(workspace_id, category_id)
  File "/Users/martin/Documents/GitHub/label-sleuth/label_sleuth/orchestrator/orchestrator_api.py", line 341, in _delete_category_models
    for idx in range(len(workspace.categories[category_id].iterations)):
AttributeError: 'NoneType' object has no attribute 'iterations'
```

**What is the expected behavior?**
The workspace should be deleted.

**Steps to reproduce the problem:**

 Call the `/delete_workspace` endpoint.

**Comment by martinscooper** [comment]
This issue has been solved.
