### ISSUE TITLE
500 Error when exporting predictions via REST API

### ISSUE THREAD

**Issue by credo99** [label-sleuth/label-sleuth#328]
<!-- ⚠ Please provide a clear description of the issue and include screenshots as needed. -
Trying to export the model predictions via REST API as per documentation:

Download the predictions of the model learned during iteration iteration_index for category category_id, as a csv file.

GET /workspace/<workspace_id>/export_predictions?category_id=<category_id>&iteration_index=<iteration_index>

**What is the current behavior?**
 500 Internal server error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Excerpt from label-sleuth.log

TypeError: list indices must be integers or slices, not str
2023-01-12 20:44:24,468 - ERROR - Exception on /workspace/Wiki/export_predictions [GET]
Traceback (most recent call last):
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\authentication.py", line 32, in wrapper
    return function(*args, **kwargs)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\app_utils.py", line 52, in wrapper
    return function(workspace_id, *args, **kwargs)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\app_utils.py", line 36, in wrapper
    return function(workspace_id, *args, **kwargs)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\app.py", line 871, in export_predictions
    infer_results = curr_app.orchestrator_api.infer(workspace_id, category_id, elements,
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\orchestrator\orchestrator_api.py", line 681, in infer
    iteration = iterations[iteration_index]
TypeError: list indices must be integers or slices, not str

**What is the expected behavior?**

**Steps to reproduce the problem:**

Run the following web command 

http://127.0.0.1:8000/workspace/Wiki/export_predictions?category_id=0&iteration_index=1

The error is reproductible with any iteration_index from 0..N

categorry_id was extracted from the workspace json

{"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.Workspace", "workspace_id": "Wiki", "dataset_name": "wiki_animals_2000_pages", "categories": {"0": {"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.Category", "name": "Birds", "id": 0, "description": "", "label_change_count_since_last_train": 0, "iterations": [{"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.Iteration", "model": {"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.ModelInfo", "model_id": "SVM_BOW_bee24180-92a8-11ed-9f66-f496340aee6f", "model_status": {"py/reduce": [{"py/type": "label_sleuth.models.core.model_api.ModelStatus"}, {"py/tuple": [1]}]}, "creation_date": {"py/object": "datetime.datetime", "__reduce__": [{"py/type": "datetime.datetime"}, ["B+cBDBQpJQS8QA=="]]}, "model_type": {"py/object": "label_sleuth.models.core.model_type.ModelType", "cls": {"py/type": "label_sleuth.models.svm.SVM_BOW"}, "name": "SVM_BOW"}, "train_statistics": {"train_counts": {"True": 20, "False": 5, "Weak_False": 35}}},

**Environment:**
 - OS: Windows10 Pro 19045.2364
 - Web browser: Chrome Version 103.0.5060.66 (Official Build) (64-bit)
 - Python version: 3.8

**Suggested solution (if any):**

**Comment by alonh** [comment]
Thanks for opening the bug report.
Can you share in a reply more details about the issue?
You can follow the template in the [bug report issue](https://github.com/label-sleuth/label-sleuth/issues/new?assignees=&labels=bug&template=bug_report.md&title=).
In addition, if possible, please attach the logs that can be found under `<sleuth_output_path>/logs` and in the console where Label Sleuth is running.

**Comment by credo99** [comment]
Sorry for the bug details misplacement, I had it put (can you see it, BTW?) in the ... area besides the contributor icon on the right. I will add it here as a reply also including the bug reporting tags:



<!-- ⚠ Please provide a clear description of the issue and include screenshots as needed. -
Trying to export the model predictions via REST API as per documentation:

Download the predictions of the model learned during iteration iteration_index for category category_id, as a csv file.

GET /workspace/<workspace_id>/export_predictions?category_id=<category_id>&iteration_index=<iteration_index>

**What is the current behavior?**
 500 Internal server error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Excerpt from label-sleuth.log

TypeError: list indices must be integers or slices, not str
2023-01-12 20:44:24,468 - ERROR - Exception on /workspace/Wiki/export_predictions [GET]
Traceback (most recent call last):
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\authentication.py", line 32, in wrapper
    return function(*args, **kwargs)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\app_utils.py", line 52, in wrapper
    return function(workspace_id, *args, **kwargs)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\app_utils.py", line 36, in wrapper
    return function(workspace_id, *args, **kwargs)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\app.py", line 871, in export_predictions
    infer_results = curr_app.orchestrator_api.infer(workspace_id, category_id, elements,
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\orchestrator\orchestrator_api.py", line 681, in infer
    iteration = iterations[iteration_index]
TypeError: list indices must be integers or slices, not str


**What is the expected behavior?**


**Steps to reproduce the problem:**

Run the following web command 

http://127.0.0.1:8000/workspace/Wiki/export_predictions?category_id=0&iteration_index=1

The error is reproductible with any iteration_index from 0..N

categorry_id was extracted from the workspace json

{"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.Workspace", "workspace_id": "Wiki", "dataset_name": "wiki_animals_2000_pages", "categories": {"0": {"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.Category", "name": "Birds", "id": 0, "description": "", "label_change_count_since_last_train": 0, "iterations": [{"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.Iteration", "model": {"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.ModelInfo", "model_id": "SVM_BOW_bee24180-92a8-11ed-9f66-f496340aee6f", "model_status": {"py/reduce": [{"py/type": "label_sleuth.models.core.model_api.ModelStatus"}, {"py/tuple": [1]}]}, "creation_date": {"py/object": "datetime.datetime", "__reduce__": [{"py/type": "datetime.datetime"}, ["B+cBDBQpJQS8QA=="]]}, "model_type": {"py/object": "label_sleuth.models.core.model_type.ModelType", "cls": {"py/type": "label_sleuth.models.svm.SVM_BOW"}, "name": "SVM_BOW"}, "train_statistics": {"train_counts": {"True": 20, "False": 5, "Weak_False": 35}}},

**Environment:**
 - OS: Windows10 Pro 19045.2364
 - Web browser: Chrome Version 103.0.5060.66 (Official Build) (64-bit)
 - Python version: 3.8

**Suggested solution (if any):**

**Comment by credo99** [comment]
Please provide a clear description of the issue and include screenshots as needed:

Trying to export the model predictions via REST API as per documentation:

Download the predictions of the model learned during iteration iteration_index for category category_id, as a csv file.

GET /workspace/<workspace_id>/export_predictions?category_id=<category_id>&iteration_index=<iteration_index>

**What is the current behavior?**

 500 Internal server error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Excerpt from label-sleuth.log

TypeError: list indices must be integers or slices, not str
2023-01-12 20:44:24,468 - ERROR - Exception on /workspace/Wiki/export_predictions [GET]
Traceback (most recent call last):
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\authentication.py", line 32, in wrapper
    return function(*args, **kwargs)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\app_utils.py", line 52, in wrapper
    return function(workspace_id, *args, **kwargs)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\app_utils.py", line 36, in wrapper
    return function(workspace_id, *args, **kwargs)
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\app.py", line 871, in export_predictions
    infer_results = curr_app.orchestrator_api.infer(workspace_id, category_id, elements,
  File "C:\Radu\Miniconda3\envs\label-sleuth\lib\site-packages\label_sleuth\orchestrator\orchestrator_api.py", line 681, in infer
    iteration = iterations[iteration_index]
TypeError: list indices must be integers or slices, not str



*Steps to reproduce the problem:**

Run the following web command 

http://127.0.0.1:8000/workspace/Wiki/export_predictions?category_id=0&iteration_index=1

The error is reproductible with any iteration_index from 0..N

categorry_id was extracted from the workspace json

{"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.Workspace", "workspace_id": "Wiki", "dataset_name": "wiki_animals_2000_pages", "categories": {"0": {"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.Category", "name": "Birds", "id": 0, "description": "", "label_change_count_since_last_train": 0, "iterations": [{"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.Iteration", "model": {"py/object": "label_sleuth.orchestrator.core.state_api.orchestrator_state_api.ModelInfo", "model_id": "SVM_BOW_bee24180-92a8-11ed-9f66-f496340aee6f", "model_status": {"py/reduce": [{"py/type": "label_sleuth.models.core.model_api.ModelStatus"}, {"py/tuple": [1]}]}, "creation_date": {"py/object": "datetime.datetime", "__reduce__": [{"py/type": "datetime.datetime"}, ["B+cBDBQpJQS8QA=="]]}, "model_type": {"py/object": "label_sleuth.models.core.model_type.ModelType", "cls": {"py/type": "label_sleuth.models.svm.SVM_BOW"}, "name": "SVM_BOW"}, "train_statistics": {"train_counts": {"True": 20, "False": 5, "Weak_False": 35}}},

**Environment:**
 - OS: Windows10 Pro 19045.2364
 - Web browser: Chrome Version 103.0.5060.66 (Official Build) (64-bit)
 - Python version: 3.8

**Comment by alonh** [comment]
Thank you for finding this issue.
This is indeed a bug in the export_predictions API call. The iteration index should be converted to an integer. 
We will implement a fix and release a new version soon.

**Comment by alonh** [comment]
fixed in v0.8.2
