### ISSUE TITLE
Error when using datasets without document id

### ISSUE THREAD

**Issue by yoavkatz** [label-sleuth/label-sleuth#332]
**What is the current behavior?**

When loading a dataset with no document id, a default document name is created based on the date.  After annotating and training the model, clicking on the next to label element fails.  The log in the message:

2023-01-15 19:34:39,584 ERROR    [app.py:1455] Exception on /workspace/Ledgar/document/Ledgar-15_Jan_2023_15 [GET]
Traceback (most recent call last):
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/label_sleuth/authentication.py", line 32, in wrapper
    return function(*args, **kwargs)
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/label_sleuth/app_utils.py", line 36, in wrapper
    return function(workspace_id, *args, **kwargs)
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/label_sleuth/app.py", line 436, in get_document_elements
    document = curr_app.orchestrator_api.get_documents(workspace_id, dataset_name, [document_uri])[0]
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/label_sleuth/orchestrator/orchestrator_api.py", line 164, in get_documents
    return self.data_access.get_documents(workspace_id, dataset_name, uris)
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/label_sleuth/data_access/file_based/file_based_data_access.py", line 192, in get_documents
    docs = [load_doc(uri) for uri in uris]
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/label_sleuth/data_access/file_based/file_based_data_access.py", line 192, in <listcomp>
    docs = [load_doc(uri) for uri in uris]
  File "/Users/yoavkatz/opt/miniconda3/envs/label-sleuth/lib/python3.8/site-packages/label_sleuth/data_access/file_based/file_based_data_access.py", line 186, in load_doc
    with open(file_path + '.json') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yoavkatz/label-sleuth/data_access_dumps/Ledgar/doc_dump/Ledgar-15_Jan_2023_15.json'

The real filename is:

/Users/yoavkatz/label-sleuth/data_access_dumps/Ledgar/doc_dump/Ledgar-15_Jan_2023_15-25-05.json 

**What is the expected behavior?**

**Steps to reproduce the problem:**

1. Load a dataset without document id
2. Create a category
3. Label enough for a model to be trained
4. Move to Next to label and click on an element

**Environment:**
 - OS: MacOs
 - Web browser: Safari
 - Python version: 3.8
 - Label Sleuth version (as it appears on the bottom left of the UI): 
Version: 0.8.1

**Suggested solution (if any):**

**Comment by alonh** [comment]
Thank you for identifying the issue. The problem was in the function that extracts document URI from element URI which did not support dashes.
 fixed in #333

**Comment by alonh** [comment]
fixed in v0.8.2
