### ISSUE TITLE
error in uploading labelled data

### ISSUE THREAD

**Issue by charliejeynes** [label-sleuth/label-sleuth#499]
**What is the current behavior?**
error message "something went wrong" when uploading labelled data - massage in my termnal below

2023-04-21 15:59:31,981 INFO     [orchestrator_api.py:901] Importing 3149 labeled elements into workspace 'test'from 7 categories
2023-04-21 15:59:31,982 WARNING  [label_import_utils.py:47] Currently label metadata is ignored
2023-04-21 15:59:31,984 ERROR    [app.py:1455] Exception on /workspace/test/import_labels [POST]
Traceback (most recent call last):
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/label_sleuth/authentication.py", line 32, in wrapper
    return function(*args, **kwargs)
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/label_sleuth/app_utils.py", line 36, in wrapper
    return function(workspace_id, *args, **kwargs)
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/label_sleuth/app.py", line 746, in import_labels
    return jsonify(curr_app.orchestrator_api.import_category_labels(workspace_id, df))
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/label_sleuth/orchestrator/orchestrator_api.py", line 909, in import_category_labels
    process_labels_dataframe(workspace_id, dataset_name, self.data_access, labels_df_to_import,
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/label_sleuth/data_access/label_import_utils.py", line 53, in process_labels_dataframe
    labels_df_to_import[DisplayFields.doc_id] = labels_df_to_import[DisplayFields.doc_id].apply(
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/pandas/core/series.py", line 4771, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/pandas/core/apply.py", line 1123, in apply
    return self.apply_standard()
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/pandas/core/apply.py", line 1174, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "/Users/charliejeynes/anaconda3/envs/label-sleuth/lib/python3.9/site-packages/label_sleuth/data_access/label_import_utils.py", line 54, in <lambda>
    lambda x: x.replace(URI_SEP, '_'))
AttributeError: 'int' object has no attribute 'replace'

**What is the expected behavior?**
It should upload labelled data (I have labelled the columns as you say)

**Steps to reproduce the problem:**

1. process my data with the four columns headers as you say 
2. save as a csv
3. upload

PS I process my df like this  - is it OK?

    def process_labelled_data_for_sleuth(df,
                                         text:str = 'sentence',
                                         label:int = 1,
                                         category_name:str = 'category',
                                         document_id:str = 'doc_id'):
        """

        :param df:
        :param text:
        :param label: all true, as here we are uploading already labelled data
        :param category_name:
        :param document_id:
        :return:
        """

        df = df.loc[:, [text, category_name, document_id]]
        df['label'] = label
        df = df.rename(columns={text:'text', category_name:'category_name', document_id:'document_id'})
        df.to_csv('../models_and_labelled_data/factuality_labelled_data.csv')
        return df

    df_ls = process_labelled_data_for_sleuth(df)

**Environment:**
 - OS: mac ventura
 - Web browser: chrome
 - Python version: 3.8
 - Label Sleuth version (as it appears on the bottom left of the UI): 0.9.4
  

**Suggested solution (if any):**
Am i on the latest version of label-sleuth?

**Comment by yannisk2** [comment]
Hi @charliejeynes,

Are the document ids by any chance numbers? Based on the exception and a quick test, there seems to be an issue with the label upload when document ids are integers. Please let us know if this is what is causing the error in your case.  

If this is indeed the error, here are a few suggestions on how to avoid this error, while we work on a fix:
- Use document names that are not numbers (e.g., by prefixing them with a string, such as `d1`, `d2`, ...)
- Convert the `document_id` column in your dataframe to type `str` and instruct the `to_csv` function to put quotes around non-numeric columns, as described in the top ranked answer at: https://stackoverflow.com/questions/41960346/how-to-add-quotes-to-every-element-in-non-numeric-column-of-a-dataframe-save

**Comment by charliejeynes** [comment]
@yannisk2 thanks very much for the reply!! just to let you know . . .

- so your first bullet point works
- your second one does **not** work 

BUt i also realised I didn't actiually need to add the doc ID anyway  - because i uploaded this data when I made the workspace, and the doc_ID loaded in just fine. So another fix is to  . . . 
- just not include a doc id for the labelled data

thanks!!

Charlie 

PS this package is AWESOME!!!!!!

**Comment by arielge** [comment]
Hi @charliejeynes! 
That's right - under the default system configuration, specifically with the parameter `apply_labels_to_duplicate_texts` set to `True`, label upload is done via a _direct string match_ and so the doc ID column is indeed not needed.

In any case, we will fix the bug with the integer doc IDs.
